window.ITDOR_PORTFOLIO = [
  {
    slug: "ecommerce-platform",
    id: "1",
    title: "E-Commerce Platform",
    category: "Web Development",
    description: "Full-stack e-commerce solution built with Next.js, featuring real-time inventory management, payment integration, and admin dashboard.",
    shortDesc: "Full-stack online store with real-time inventory, payments, and admin dashboard.",
    image: "image/portfolio/ecommerce.avif",
    gallery: ["image/portfolio/ecommerce.avif", "image/portfolio/ecommerce-screenshot.jpg", "image/portfolio/web-development.webp"],
    technologies: ["Next.js", "React", "TypeScript", "Stripe", "PostgreSQL"],
    client: "Retail & E-Commerce",
    location: "Boston, MA, USA",
    published: "2025",
    featured: true
  },
  {
    slug: "saas-dashboard",
    id: "2",
    title: "SaaS Dashboard",
    category: "Web Development",
    description: "Modern SaaS application with user authentication, subscription management, and analytics dashboard.",
    shortDesc: "Analytics and subscription management with role-based access and reporting.",
    image: "image/portfolio/saas-dashboard.png",
    gallery: ["image/portfolio/saas-dashboard.png", "image/portfolio/saas-screenshot.jpg", "image/portfolio/web-development.webp"],
    technologies: ["React", "Node.js", "MongoDB", "Stripe", "AWS"],
    client: "SaaS & Technology",
    location: "Boston, MA, USA",
    published: "2025",
    featured: true
  },
  {
    slug: "corporate-website",
    id: "3",
    title: "Corporate Website",
    category: "Web Development",
    description: "High-performance corporate website with CMS integration, SEO optimization, and multilingual support.",
    shortDesc: "High-performance corporate site with CMS integration and SEO optimization.",
    image: "image/portfolio/web-development.webp",
    gallery: ["image/portfolio/web-development.webp", "image/portfolio/ecommerce-screenshot.jpg", "image/portfolio/marketplace.jpg"],
    technologies: ["Next.js", "Contentful", "Tailwind CSS", "Vercel"],
    client: "Enterprise",
    location: "Boston, MA, USA",
    published: "2025"
  },
  {
    slug: "fitness-tracking-app",
    id: "4",
    title: "Mobile Fitness App",
    category: "Mobile Development",
    description: "Cross-platform mobile app for fitness tracking with workout plans, progress monitoring, and social features.",
    shortDesc: "Cross-platform app for workouts, progress tracking, and social features.",
    image: "image/portfolio/fitness-app.png",
    gallery: ["image/portfolio/fitness-app.png", "image/portfolio/mobile-development.webp", "image/portfolio/food-delivery.jpg"],
    technologies: ["React Native", "Firebase", "Redux", "iOS", "Android"],
    client: "Health & Fitness",
    location: "Boston, MA, USA",
    published: "2025",
    featured: true
  },
  {
    slug: "food-delivery-app",
    id: "5",
    title: "Food Delivery App",
    category: "Mobile Development",
    description: "Native mobile application for food ordering with real-time tracking, payment processing, and push notifications.",
    shortDesc: "Food ordering app with real-time tracking, payments, and push notifications.",
    image: "image/portfolio/food-delivery.jpg",
    gallery: ["image/portfolio/food-delivery.jpg", "image/portfolio/mobile-development.webp", "image/portfolio/fitness-app.png"],
    technologies: ["Flutter", "Dart", "Firebase", "Stripe", "Google Maps"],
    client: "Food & Logistics",
    location: "Boston, MA, USA",
    published: "2025"
  },
  {
    slug: "banking-app-redesign",
    id: "6",
    title: "Banking App Redesign",
    category: "UI/UX Design",
    description: "Complete UI/UX redesign for a mobile banking application, improving user experience and conversion rates by 40%.",
    shortDesc: "Mobile banking redesign focused on usability and conversion improvement.",
    image: "image/portfolio/fintech.jpg",
    gallery: ["image/portfolio/fintech.jpg", "image/portfolio/design.webp", "image/portfolio/saas-dashboard.png"],
    technologies: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    client: "Financial Services",
    location: "Boston, MA, USA",
    published: "2025"
  },
  {
    slug: "healthcare-portal",
    id: "7",
    title: "Healthcare Portal Design",
    category: "UI/UX Design",
    description: "User-centered design for a patient portal with focus on accessibility and ease of use.",
    shortDesc: "Patient portal design with accessibility and ease of use at the center.",
    image: "image/portfolio/healthcare.jpg",
    gallery: ["image/portfolio/healthcare.jpg", "image/portfolio/healthcare-screenshot.jpg", "image/portfolio/design.webp"],
    technologies: ["Figma", "Design Systems", "Accessibility", "WCAG"],
    client: "Healthcare",
    location: "Boston, MA, USA",
    published: "2025"
  },
  {
    slug: "chatbot-platform",
    id: "8",
    title: "AI Customer Assistant",
    category: "AI Solutions",
    description: "AI-powered customer service chatbot with natural language processing and multi-language support.",
    shortDesc: "Chatbot with NLP and multi-language support for support and sales.",
    image: "image/portfolio/ai-assistant.png",
    gallery: ["image/portfolio/ai-assistant.png", "image/portfolio/ai-screenshot.jpg", "image/portfolio/ai-solutions.webp"],
    technologies: ["Python", "OpenAI", "NLP", "FastAPI", "Docker"],
    client: "Customer Support",
    location: "Boston, MA, USA",
    published: "2025",
    featured: true
  },
  {
    slug: "predictive-analytics",
    id: "9",
    title: "Predictive Analytics Dashboard",
    category: "AI Solutions",
    description: "Machine learning platform for business intelligence with predictive analytics and data visualization.",
    shortDesc: "ML platform for business intelligence with predictive analytics and visualization.",
    image: "image/portfolio/ai-solutions.webp",
    gallery: ["image/portfolio/ai-solutions.webp", "image/portfolio/ai-screenshot.jpg", "image/portfolio/saas-dashboard.png"],
    technologies: ["Python", "TensorFlow", "React", "PostgreSQL", "AWS"],
    client: "Analytics & BI",
    location: "Boston, MA, USA",
    published: "2025"
  },
  {
    slug: "microservices-architecture",
    id: "10",
    title: "Microservices Architecture",
    category: "Cloud Services",
    description: "Scalable cloud infrastructure with microservices architecture, containerization, and CI/CD pipelines.",
    shortDesc: "Scalable cloud infrastructure with microservices and containerization.",
    image: "image/portfolio/cloud-services.webp",
    gallery: ["image/portfolio/cloud-services.webp", "image/portfolio/devops.webp", "image/portfolio/saas-dashboard.png"],
    technologies: ["AWS", "Docker", "Kubernetes", "Terraform", "GitLab CI"],
    client: "Cloud Infrastructure",
    location: "Boston, MA, USA",
    published: "2025"
  },
  {
    slug: "cicd-pipeline",
    id: "11",
    title: "CI/CD Pipeline Setup",
    category: "DevOps & CI/CD",
    description: "Automated deployment pipeline with testing, building, and deployment to multiple environments.",
    shortDesc: "Automated deployment pipeline across testing, build, and production environments.",
    image: "image/portfolio/devops.webp",
    gallery: ["image/portfolio/devops.webp", "image/portfolio/cloud-services.webp", "image/portfolio/support.avif"],
    technologies: ["Jenkins", "Docker", "Kubernetes", "GitHub Actions", "AWS"],
    client: "DevOps & Engineering",
    location: "Boston, MA, USA",
    published: "2025"
  },
  {
    slug: "legacy-modernization",
    id: "12",
    title: "Legacy System Modernization",
    category: "Digital Transformation",
    description: "Complete digital transformation of legacy systems to modern cloud-based architecture.",
    shortDesc: "Modernization of legacy systems to cloud-based architecture.",
    image: "image/portfolio/digital-transform.jpg",
    gallery: ["image/portfolio/digital-transform.jpg", "image/portfolio/cloud-services.webp", "image/portfolio/web-development.webp"],
    technologies: ["Cloud Migration", "API Integration", "Microservices", "AWS"],
    client: "Enterprise IT",
    location: "Boston, MA, USA",
    published: "2025"
  },
  {
    slug: "monitoring-system",
    id: "13",
    title: "24/7 Monitoring System",
    category: "Support & Maintenance",
    description: "Comprehensive monitoring and maintenance solution with automated alerts and performance optimization.",
    shortDesc: "Monitoring and maintenance with automated alerts and performance tuning.",
    image: "image/portfolio/support.avif",
    gallery: ["image/portfolio/support.avif", "image/portfolio/devops.webp", "image/portfolio/cloud-services.webp"],
    technologies: ["Monitoring", "Automation", "Performance Tuning", "AWS"],
    client: "IT Operations",
    location: "Boston, MA, USA",
    published: "2025"
  }
];

window.ITDOR_PORTFOLIO_CATEGORIES = [
  "Show All",
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "AI Solutions",
  "Cloud Services",
  "DevOps & CI/CD",
  "Digital Transformation",
  "Support & Maintenance"
];

window.ITDOR_PORTFOLIO_BY_SLUG = window.ITDOR_PORTFOLIO.reduce(function (acc, item) {
  acc[item.slug] = item;
  return acc;
}, {});
