window.ITDOR_SERVICES = [
  { slug: "network-connectivity", group: "onsite", icon: "icon-mega-menu", title: "Network & End User Connectivity", description: "Resolve network and end-user connectivity issues quickly to keep your team online and productive.", intro: "We diagnose and fix connectivity problems across your office network, Wi‑Fi, VPN, and end-user devices so your team stays online.", features: ["Wi‑Fi and LAN troubleshooting", "VPN and remote access support", "Device and peripheral connectivity", "Same-day response for urgent outages", "Fully insured onsite service"], image: "image/services-item/services-1.jpg" },
  { slug: "emergency-onsite", group: "onsite", icon: "icon-send", title: "Emergency Onsite Dispatch", description: "Fast onsite response when urgent IT issues threaten your business operations.", intro: "When critical IT failures can't wait, we dispatch technicians to your location for hands-on resolution.", features: ["Rapid onsite dispatch", "Critical outage response", "Hardware and network emergencies", "Temporary workarounds when needed", "Fully insured technicians"], image: "image/services/onsite_dispatch.jpg" },
  { slug: "cat5-cat6-cabling", group: "onsite", icon: "icon-outsourcing", title: "Cat5/Cat6 Cable Installations", description: "Professional structured cabling for reliable, high-performance network infrastructure.", intro: "We design and install structured cabling systems that support reliable, high-speed connectivity across your office.", features: ["Cat5e and Cat6 installation", "Cable management and labeling", "Patch panel and rack setup", "Testing and certification", "Scalable infrastructure planning"], image: "image/services/cat5_installation.jpg" },
  { slug: "desktop-support", group: "onsite", icon: "icon-user", title: "Desktop Support", description: "Expert support for desktops, peripherals, and everyday user technology issues.", intro: "From software installs to printer problems, we keep your users productive with responsive desktop support.", features: ["Windows and Mac support", "Peripheral setup and troubleshooting", "Software installation and updates", "User account and access help", "Remote and onsite assistance"], image: "image/services-item/services-1.jpg" },
  { slug: "server-support", group: "onsite", icon: "icon-machine", title: "Server Support", description: "Maintain, monitor, and troubleshoot servers to maximize uptime and performance.", intro: "We maintain and troubleshoot physical and virtual servers to keep your business systems running reliably.", features: ["Server monitoring and maintenance", "Performance tuning", "Backup verification", "Patch and update management", "Incident response and recovery"], image: "image/services/server_support.jpg" },
  { slug: "networking-issues", group: "onsite", icon: "icon-mega-menu", title: "Networking Issues", description: "Diagnose and fix LAN/WAN, routing, and network performance problems.", intro: "We resolve LAN/WAN, routing, firewall, and performance issues affecting your network.", features: ["Router and switch configuration", "DNS and DHCP troubleshooting", "Firewall and security review", "Bandwidth and latency analysis", "Network documentation"], image: "image/services/networking_issue.jpg" },
  { slug: "voip-support", group: "onsite", icon: "icon-phone", title: "VOIP Phone Support & Installations", description: "Setup, support, and maintenance for business VOIP phone systems.", intro: "We install, configure, and support business VOIP systems for clear, reliable communications.", features: ["VOIP system setup", "Phone and extension provisioning", "Call quality troubleshooting", "Integration with existing network", "Ongoing maintenance and support"], image: "image/services/voip_installation.jpg" },
  { slug: "application-support", group: "software", icon: "icon-chat-2", title: "Application Support", description: "Dedicated support for your applications: troubleshooting, user training, and clear communication between you and the dev team.", intro: "An Application Support Specialist manages, maintains, and troubleshoots your business software—bridging the gap between technical teams and end-users.", features: ["Issue triage and resolution", "User support and training", "Dev-client communication", "Post-launch support (1 month free)", "Documentation and knowledge base"], image: "image/services/application_support.avif" },
  { slug: "software-development", group: "software", icon: "icon-custom-software", title: "Software Development", description: "Custom web, mobile, AI, and cloud solutions with modern stacks. Projects start from $3K.", intro: "We build scalable web, mobile, AI, and cloud applications with modern stacks. Every project is case by case—get in touch for a detailed quote.", features: ["Web and mobile apps (React, Next.js, Flutter)", "Backend and APIs (Node.js, Python)", "AI and data integration", "Cloud-native deployment", "1 month free support after launch"], image: "image/services/software_development.avif" },
  { slug: "ui-ux-design", group: "software", icon: "icon-augmented", title: "UI/UX Design", description: "User-centered design, prototypes, and design systems for web and mobile applications.", intro: "We create user-centered designs, prototypes, and design systems that improve usability and conversion.", features: ["User research and personas", "Wireframes and prototypes", "Design systems", "Accessibility (WCAG)", "Handoff to development"], image: "image/services/design.webp" },
  { slug: "cloud-devops", group: "software", icon: "icon-outsourcing", title: "Cloud & DevOps", description: "Infrastructure, CI/CD, cloud-native solutions, and automation on AWS, Azure, and GCP.", intro: "We build and automate cloud infrastructure with CI/CD pipelines on AWS, Azure, and GCP.", features: ["AWS, Azure, and GCP", "CI/CD pipelines", "Containers and Kubernetes", "Monitoring and alerting", "Infrastructure as Code"], image: "image/services/cloud_devops.avif" },
  { slug: "web-security", group: "software", icon: "icon-check", title: "Web Security", description: "Secure web applications, APIs, and infrastructure against common threats and abuse.", intro: "We harden web applications, APIs, and infrastructure against common threats and abuse.", features: ["OWASP-aligned reviews", "API security", "Authentication and access control", "Vulnerability assessment", "Security best practices"], image: "image/services/web_security.jpg" },
  { slug: "ai-ml", group: "software", icon: "icon-artificial", title: "AI & Machine Learning", description: "AI assistants, predictive analytics, LLM integration, and automation solutions.", intro: "We integrate AI assistants, predictive analytics, and automation into your products and workflows.", features: ["LLM and chatbot integration", "Predictive models", "Computer vision and NLP", "ML pipelines", "OpenAI and custom models"], image: "image/services/ai_machine_learning.jpg" },
  { slug: "saas", group: "software", icon: "icon-software-product", title: "SaaS Development", description: "Subscription-based web apps: CRM, project management, and business tools.", intro: "We build subscription-based SaaS products with billing, multi-tenancy, and analytics.", features: ["Multi-tenant architecture", "Subscription and billing", "Role-based access", "Analytics dashboards", "API-first design"], image: "image/services/sass.avif" },
  { slug: "ecommerce", group: "software", icon: "cart", iconType: "svg", title: "eCommerce Solutions", description: "Online stores, marketplaces, checkout, inventory, and logistics systems.", intro: "We build online stores and marketplaces with checkout, inventory, and logistics integrations.", features: ["Storefronts and marketplaces", "Checkout and payments", "Inventory and orders", "Shipping and logistics", "Admin and reporting"], image: "image/services/eCommerce.jpg" },
  { slug: "erp", group: "software", icon: "icon-outsourcing", title: "ERP & Enterprise Systems", description: "Business operations, HR, inventory, accounting, and reporting integrations.", intro: "We integrate and customize ERP systems for HR, inventory, accounting, and reporting.", features: ["HR and payroll modules", "Inventory and supply chain", "Accounting and finance", "Reporting and BI", "Third-party integrations"], image: "image/services/erp_enterprise Systems.jpg" },
  { slug: "fintech", group: "software", icon: "icon-check", title: "Finance", description: "Payments, digital banking, crypto, lending, and trading platforms.", intro: "We build fintech platforms for payments, banking, lending, and trading with compliance in mind.", features: ["Payment gateways", "KYC/AML flows", "Real-time transactions", "Compliance and reporting", "Secure data handling"], image: "image/services/fintech.avif" },
  { slug: "food-delivery", group: "software", icon: "icon-send", title: "Food Delivery & Logistics", description: "Ordering, routing, driver management, and real-time tracking.", intro: "We build food ordering and delivery platforms with real-time tracking and driver management.", features: ["Order and menu management", "Driver app and dispatch", "Real-time tracking", "Payments and payouts", "Restaurant dashboards"], image: "image/services/food_delivery.jpg" },
  { slug: "marketplace", group: "software", icon: "icon-outsourcing", title: "Marketplace Platforms", description: "Multi-vendor ecosystems with bookings, payments, and vendor onboarding.", intro: "We create multi-vendor marketplaces with search, bookings, payments, and trust systems.", features: ["Vendor onboarding", "Search and discovery", "Bookings and payments", "Reviews and trust", "Commission and payouts"], image: "image/services/marketplace.jpg" },
  { slug: "social", group: "software", icon: "icon-chat-2", title: "Social Networking", description: "Messaging, feeds, real-time interactions, and content discovery.", intro: "We build social platforms with feeds, messaging, notifications, and moderation.", features: ["Feeds and timelines", "Real-time chat", "Notifications", "Moderation tools", "Content discovery"], image: "image/services/social_network.jpg" },
  { slug: "streaming", group: "software", icon: "film", iconType: "svg", title: "Streaming & Media", description: "Video and audio delivery, live streaming, CDN, and monetization.", intro: "We deliver video and audio streaming platforms with CDN, DRM, and monetization.", features: ["Live and VOD streaming", "CDN and transcoding", "Player and DRM", "Analytics", "Monetization"], image: "image/services/streaming_media.jpg" },
  { slug: "dating", group: "software", icon: "heart", iconType: "svg", title: "Dating & Community Apps", description: "Matching algorithms, chat, moderation, and subscription features.", intro: "We build dating and community apps with matching, chat, safety, and subscriptions.", features: ["Matching algorithms", "Chat and video", "Safety and moderation", "Discovery and filters", "Subscriptions"], image: "image/services/dating_community.jpg" },
  { slug: "healthtech", group: "software", icon: "icon-star-of-life", title: "Health", description: "Telemedicine, patient portals, HIPAA-compliant data, and EHR integration.", intro: "We build healthcare platforms with telemedicine, patient portals, and HIPAA-aware design.", features: ["Telemedicine and video visits", "Patient portals", "HIPAA-compliant data", "EHR integration", "Scheduling and reminders"], image: "image/services/healthtech.avif" },
  { slug: "edtech", group: "software", icon: "icon-quote", title: "Education", description: "Learning platforms, course systems, assessments, and AI tutors.", intro: "We create learning platforms with courses, assessments, and AI-powered tutoring.", features: ["LMS and course delivery", "Assessments and progress", "AI tutors", "Certifications", "Collaboration tools"], image: "image/services/learning.avif" },
  { slug: "proptech", group: "software", icon: "icon-location-dot", title: "Real Estate", description: "Property listings, virtual tours, document workflows, and agent tools.", intro: "We build proptech solutions for listings, virtual tours, documents, and agent workflows.", features: ["Listings and search", "Virtual tours", "Document and e-sign", "Agent tools", "Transaction workflows"], image: "image/services/proptteh_realestate.jpg" },
  { slug: "legaltech", group: "software", icon: "scale", iconType: "svg", title: "Legal", description: "Contract automation, compliance tracking, and document analysis.", intro: "We automate legal workflows with contract drafting, e-sign, and compliance tracking.", features: ["Contract templates", "E-sign and workflow", "Compliance tracking", "Document analysis", "Case management"], image: "image/services/legal_tech.jpg" },
  { slug: "travel", group: "software", icon: "icon-calendar-days", title: "Travel & Hospitality", description: "Booking engines, itineraries, loyalty programs, and channel managers.", intro: "We build booking engines and itinerary tools for travel and hospitality businesses.", features: ["Booking engines", "Inventory and rates", "Itineraries", "Loyalty programs", "Channel managers"], image: "image/services/travel_hospitality.avif" },
  { slug: "blockchain", group: "software", icon: "icon-outsourcing", title: "Blockchain & Web3", description: "Smart contracts, DeFi, wallets, dApps, and decentralized identity.", intro: "We develop Web3 solutions including smart contracts, wallets, and dApps.", features: ["Smart contracts", "DeFi protocols", "Wallets and dApps", "Decentralized identity", "Tokenization"], image: "image/services/blockchain.jpg" },
  { slug: "pwa-api", group: "software", icon: "icon-custom-software", title: "PWA & API Development", description: "Progressive web apps, REST/GraphQL APIs, and third-party integrations.", intro: "We build PWAs, REST/GraphQL APIs, and integration backends for web and mobile.", features: ["Progressive Web Apps", "REST and GraphQL APIs", "Third-party integrations", "Webhooks and real-time", "Documentation and SDKs"], image: "image/services/pwa_api.jpg" },
  { slug: "smart-city", group: "software", icon: "city", iconType: "svg", title: "Smart City Solutions", description: "Traffic management, smart parking, surveillance, and environmental monitoring.", intro: "We build smart city systems for traffic, parking, surveillance, and environmental data.", features: ["Traffic management", "Smart parking", "Surveillance and safety", "Environmental monitoring", "Data analytics"], image: "image/services/smart_city.jpg" },
  { slug: "mobility", group: "software", icon: "car", iconType: "svg", title: "Mobility & Ride-Sharing", description: "Ride-hailing apps, fleet management, route optimization, and EV charging.", intro: "We create ride-hailing and fleet management platforms with route optimization.", features: ["Ride-hailing apps", "Fleet management", "Route optimization", "EV charging networks", "Driver and rider apps"], image: "image/services/mobile_ride.jpg" },
  { slug: "retailtech", group: "software", icon: "icon-software-product", title: "Retail & POS", description: "Point-of-sale systems, inventory automation, self-checkout, and omnichannel.", intro: "We build POS and retail systems with inventory automation and omnichannel support.", features: ["Point-of-sale systems", "Inventory automation", "Self-checkout kiosks", "Customer analytics", "Omnichannel retail"], image: "image/services/retailtech_pos.jpg" },
  { slug: "hrtech", group: "software", icon: "icon-user", title: "HR & Workforce", description: "Recruitment, payroll, performance analytics, and remote workforce tools.", intro: "We develop HR platforms for recruitment, payroll, performance, and remote teams.", features: ["Recruitment and ATS", "Payroll and benefits", "Performance analytics", "Remote workforce tools", "Employee portals"], image: "image/services/hr_tech.jpg" },
  { slug: "climatetech", group: "software", icon: "cloud", iconType: "svg", title: "Climate & Sustainability", description: "Carbon tracking, energy optimization, ESG reporting, and sustainable supply chain.", intro: "We build climate tech for carbon tracking, energy optimization, and ESG reporting.", features: ["Carbon tracking", "Energy optimization", "Renewable monitoring", "ESG reporting", "Sustainable supply chain"], image: "image/services/climate_sustainability.jpg" }
];

window.ITDOR_SERVICES_BY_SLUG = window.ITDOR_SERVICES.reduce(function (acc, s) {
  acc[s.slug] = s;
  return acc;
}, {});
